steps:
    - id: install
      name: 'node:20-alpine'
      entrypoint: npm
      args: ['ci']

    - id: build
      name: 'node:20-alpine'
      entrypoint: npm
      args: ['run', 'build']

    - id: deploy
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'bash'
      args:
          [
              '-c',
              'gcloud config set app/cloud_build_timeout 600 && gcloud app deploy',
          ]

options:
    logging: CLOUD_LOGGING_ONLY

timeout: '600s'
